### ISSUE TITLE
怎么这就破防了啊？

### ISSUE THREAD

**Issue by singer01** [Chihaya-Yuka/OpenCopilot#3]
额

**Comment by cmd1152** [comment]
乐

**Comment by Remelens** [comment]
崩

**Comment by zhiziqxd** [comment]
申金啊

**Comment by singer01** [comment]
打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！

**Comment by singer01** [comment]
> 乐

打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！

**Comment by singer01** [comment]
这件事和其他人无关，但是MelonCmd把我block了，破防了

**Comment by zhiziqxd** [comment]
@singer01 打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!

**Comment by singer01** [comment]
> @singer01 打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!打倒不吃香菜暴政!

怎么破防了？

**Comment by singer01** [comment]
> 乐

我服了，快让我进去

**Comment by singer01** [comment]
> 崩

Please Unban ME
