### ISSUE TITLE
GPCR的自述

### ISSUE THREAD

**Issue by singer01** [Chihaya-Yuka/OpenCopilot#4]
你们，攻击GPCR的那些人，说的这些那可以说是鸡蛋里面挑骨头，挑来挑去。采用了没有的给我捏造，小事情给我夸大，别人的加在我头上，用这样的方法来制造了这起大大的冤案。你们开了这个头，好，后人就会群起而校之。我所干的这一切，包括你们现在在台上的绝大多数人都曾经异口同声地拥护过，参加过，你们又怎样解释你们当年的行为呢？我就是和尚打伞——无法无天。大不了杀头。我是孙悟空，我能变几个脑袋，你砍几个，我长几个。杀我灭口，光荣之甚。这就是我的回答！

**Comment by singer01** [comment]
@0x24a

**Comment by singer01** [comment]
@MelonCmd

**Comment by singer01** [comment]
项庄舞剑，意在沛公。

投降叛变，授人以柄。

要害问题，两个纲领：

以阶级斗争为纲，

纲举目张，继续革命；

以三项指示为纲，

以目混纲，修正反动。

穷凶极恶，大现原形。

掩盖罪恶，画皮美容。

树立威信，欺世盗名。

标新立异，妖言惑众。

弥天大谎，隐瞒真情。

偷天换日伎俩，上下其手劣行。

张冠李戴强加，移花接木暗中。

转移人民视线，推责盗誉缺公。

栽赃嫁祸他人，妄图洗刷臭名；

罗织诬陷中央文革，迫害灭口有关知情。

只手难掩天下耳目，笑修正主义螳臂之辈。

推动世界的动力，乃是人民大众英雄。

……

清君之侧，目的在‘君’。

罗织陷害，血口喷人。

利用专政，搞法西斯。

精神虐待，一言难尽。

破坏政策，凶悍残暴。

造反有理，革命无罪。

杀我灭口，光荣之甚。

**Comment by singer01** [comment]
NOT COMPLETED

**Comment by Chihaya-Yuka** [comment]
> 未完成

灯

自顾自地闪烁

照亮普通的我 在角落里蜷缩

生来就笨拙 越努力越犯错

把真心藏进笔记 任自己撕扯

张开口 又该说些什么

言语积攒太多 却只留下沉默

这世界喧嚣着 如同末班列车

擦肩而过

你听 你听 生命在高歌

咀嚼青春的苦涩 写下属于你的 乐章

走吧 走吧 哪怕再迷茫

群星终将照耀你前方

啊——

一场偶然 心和心做交换

一个人的呐喊 变成两份勇敢

犹豫着 退缩者 不安的 自卑的

想要成为人类的我 原来不孤单

让我欢笑落泪 让我大声歌唱

让我在你身旁 骄傲的绽放

感谢你 告诉我

平凡如石子也能变成光

啊 像上错了列车

经过意外景色 也终究是过客

如果敞开心 只能换来隔阂

该不该放弃勇气 做个旁观者

难道说 成长就是褪色

学会筑起外壳 不再期待什么

无休止的坠落 被戳穿的泡沫

谁能来拯救我

啊——

欢喜一场 才知光阴无常

留下甜美的糖 刻下隐晦的伤

越不想 越去想 越追问 越迷茫

是不是所有相遇 都注定散场

我还不想忘记 不愿就此放弃

一味逃避感伤 有什么意义

等奇迹 先来临

或许不如相信自己

噢 一行两行

写下一行两行

没能说出口的 变成诗歌 填满了纸张

噢 想要歌唱

哪怕独自歌词

牵绊化为歌声 能不能传达你的身旁

「普通」却长久的陪伴 曾经认为「理所当然」

原来我早就习惯你给我的勇敢

现在的我

终于能够为你

放声高歌

被人伤过 何必强作洒脱

爱慕虚荣 有什么过错

谁不曾想过做英雄 想有人懂

想要忠实观众 想象王冠轻重

挣扎过 失败过 一起重新来过

互相舔舐伤口 就更快愈合

一辈子

没多久

最幸福不过被人需要着

啊——

让这歌声 粉碎心中隔阂

哪怕声嘶力竭

也想对你诉说

彼此都 失去过

凭什么 再错过

任此刻世界泯灭 我不会放手

「正确」的 「普通」的 究竟都是什么

也许一起犯错 才能够懂得

没关系 抬起头

有谁的青春不曾迷路过

啊

下一个 岔路口

向左向右都陪我一起走

你听 你听 生命在高歌

咀嚼青春的苦涩 写下属于你的 乐章

走吧 走吧 哪怕再迷茫

群星终将照亮你 一定会照亮你 的方向

一点 一滴 心中积累着

每个闪光的时刻 汇成璀璨银河 来吧

全力 迸发 年轻的炽热

化作最明亮灯火

和群星共闪烁

**Comment by singer01** [comment]
# 水调歌头·粉碎走资派 
大快人心事，揪斗走资派，阴谋篡党夺权，叛党皆兵败，中式赫鲁晓夫，自比改开伟人，五六扫而光，妄成寡头者，一枕梦黄粱。开小会，走小道，吃小灶，真是无法无天，阴谋害小王，接班人是俊杰，继得遗志真传，功绩何辉煌，拥护毛主席，拥护党中央。
